# Generated by Django 4.2.4 on 2023-08-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('pelicula', 'Pelicula'), ('serie', 'Serie')], max_length=10)),
                ('no_visualizaciones', models.IntegerField()),
                ('puntaje', models.FloatField()),
            ],
        ),
    ]
