# Generated by Django 4.2.4 on 2023-08-24 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_mediacatalog_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediausuarios',
            old_name='media',
            new_name='media_id',
        ),
        migrations.RenameField(
            model_name='mediausuarios',
            old_name='usuario',
            new_name='usuario_id',
        ),
        migrations.RenameField(
            model_name='mediausuarioscount',
            old_name='media',
            new_name='media_id',
        ),
    ]
