# Generated by Django 4.2.4 on 2023-08-24 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_rename_media_mediausuarios_media_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediausuarios',
            old_name='media_id',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='mediausuarios',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='mediausuarioscount',
            old_name='media_id',
            new_name='media',
        ),
    ]
