# Generated by Django 4.2.4 on 2023-08-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_rename_media_id_mediausuarios_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediausuarioscount',
            name='avg_score',
            field=models.FloatField(null=True),
        ),
    ]
